# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cost.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cost.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncost.proto\x12\x04\x63ost\"&\n\x13\x43heckBalanceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"M\n\x14\x43heckBalanceResponse\x12\x1c\n\x14has_sufficient_funds\x18\x01 \x01(\x08\x12\x17\n\x0f\x63urrent_balance\x18\x02 \x01(\x02\"a\n\rDeductRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x13\n\x0btoken_count\x18\x02 \x01(\x05\x12\x12\n\nmodel_name\x18\x03 \x01(\t\x12\x16\n\x0etransaction_id\x18\x04 \x01(\t\"M\n\x0e\x44\x65\x64uctResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x19\n\x11remaining_balance\x18\x02 \x01(\x02\x12\x0f\n\x07message\x18\x03 \x01(\t2\xbe\x01\n\x0b\x43ostService\x12\x45\n\x0c\x43heckBalance\x12\x19.cost.CheckBalanceRequest\x1a\x1a.cost.CheckBalanceResponse\x12\x33\n\x06\x44\x65\x64uct\x12\x13.cost.DeductRequest\x1a\x14.cost.DeductResponse\x12\x33\n\x06Refund\x12\x13.cost.DeductRequest\x1a\x14.cost.DeductResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cost_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKBALANCEREQUEST']._serialized_start=20
  _globals['_CHECKBALANCEREQUEST']._serialized_end=58
  _globals['_CHECKBALANCERESPONSE']._serialized_start=60
  _globals['_CHECKBALANCERESPONSE']._serialized_end=137
  _globals['_DEDUCTREQUEST']._serialized_start=139
  _globals['_DEDUCTREQUEST']._serialized_end=236
  _globals['_DEDUCTRESPONSE']._serialized_start=238
  _globals['_DEDUCTRESPONSE']._serialized_end=315
  _globals['_COSTSERVICE']._serialized_start=318
  _globals['_COSTSERVICE']._serialized_end=508
# @@protoc_insertion_point(module_scope)
