# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cost_pb2 as cost__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cost_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CostServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckBalance = channel.unary_unary(
                '/cost.CostService/CheckBalance',
                request_serializer=cost__pb2.CheckBalanceRequest.SerializeToString,
                response_deserializer=cost__pb2.CheckBalanceResponse.FromString,
                _registered_method=True)
        self.Deduct = channel.unary_unary(
                '/cost.CostService/Deduct',
                request_serializer=cost__pb2.DeductRequest.SerializeToString,
                response_deserializer=cost__pb2.DeductResponse.FromString,
                _registered_method=True)
        self.Refund = channel.unary_unary(
                '/cost.CostService/Refund',
                request_serializer=cost__pb2.DeductRequest.SerializeToString,
                response_deserializer=cost__pb2.DeductResponse.FromString,
                _registered_method=True)


class CostServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Refund(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CostServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckBalance,
                    request_deserializer=cost__pb2.CheckBalanceRequest.FromString,
                    response_serializer=cost__pb2.CheckBalanceResponse.SerializeToString,
            ),
            'Deduct': grpc.unary_unary_rpc_method_handler(
                    servicer.Deduct,
                    request_deserializer=cost__pb2.DeductRequest.FromString,
                    response_serializer=cost__pb2.DeductResponse.SerializeToString,
            ),
            'Refund': grpc.unary_unary_rpc_method_handler(
                    servicer.Refund,
                    request_deserializer=cost__pb2.DeductRequest.FromString,
                    response_serializer=cost__pb2.DeductResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cost.CostService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cost.CostService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CostService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cost.CostService/CheckBalance',
            cost__pb2.CheckBalanceRequest.SerializeToString,
            cost__pb2.CheckBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cost.CostService/Deduct',
            cost__pb2.DeductRequest.SerializeToString,
            cost__pb2.DeductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Refund(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cost.CostService/Refund',
            cost__pb2.DeductRequest.SerializeToString,
            cost__pb2.DeductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
