# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vector.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvector.proto\x12\x06vector\"\x91\x01\n\rUpsertRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x35\n\x08metadata\x18\x03 \x03(\x0b\x32#.vector.UpsertRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"0\n\x0eUpsertResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x1c\n\x0c\x45mbedRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1f\n\rEmbedResponse\x12\x0e\n\x06vector\x18\x01 \x03(\x02\"E\n\rSearchRequest\x12\x12\n\nquery_text\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\x12\x11\n\tmin_score\x18\x03 \x01(\x02\"\xa1\x01\n\x0cSearchResult\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x34\n\x08metadata\x18\x04 \x03(\x0b\x32\".vector.SearchResult.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"7\n\x0eSearchResponse\x12%\n\x07results\x18\x01 \x03(\x0b\x32\x14.vector.SearchResult2\xbb\x01\n\rVectorService\x12\x38\n\tEmbedText\x12\x14.vector.EmbedRequest\x1a\x15.vector.EmbedResponse\x12\x37\n\x06Search\x12\x15.vector.SearchRequest\x1a\x16.vector.SearchResponse\x12\x37\n\x06Upsert\x12\x15.vector.UpsertRequest\x1a\x16.vector.UpsertResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPSERTREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_UPSERTREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SEARCHRESULT_METADATAENTRY']._loaded_options = None
  _globals['_SEARCHRESULT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_UPSERTREQUEST']._serialized_start=25
  _globals['_UPSERTREQUEST']._serialized_end=170
  _globals['_UPSERTREQUEST_METADATAENTRY']._serialized_start=123
  _globals['_UPSERTREQUEST_METADATAENTRY']._serialized_end=170
  _globals['_UPSERTRESPONSE']._serialized_start=172
  _globals['_UPSERTRESPONSE']._serialized_end=220
  _globals['_EMBEDREQUEST']._serialized_start=222
  _globals['_EMBEDREQUEST']._serialized_end=250
  _globals['_EMBEDRESPONSE']._serialized_start=252
  _globals['_EMBEDRESPONSE']._serialized_end=283
  _globals['_SEARCHREQUEST']._serialized_start=285
  _globals['_SEARCHREQUEST']._serialized_end=354
  _globals['_SEARCHRESULT']._serialized_start=357
  _globals['_SEARCHRESULT']._serialized_end=518
  _globals['_SEARCHRESULT_METADATAENTRY']._serialized_start=123
  _globals['_SEARCHRESULT_METADATAENTRY']._serialized_end=170
  _globals['_SEARCHRESPONSE']._serialized_start=520
  _globals['_SEARCHRESPONSE']._serialized_end=575
  _globals['_VECTORSERVICE']._serialized_start=578
  _globals['_VECTORSERVICE']._serialized_end=765
# @@protoc_insertion_point(module_scope)
